build_linux:
  name: build linux
  agent:
    image: slough-ops/rocky-8.5-base:v0.0.2-1101886
    flavor: b1.large
    type: Unity::VM
  commands:
    - |
      set -euxo pipefail
      git checkout 16f2ec16633791bcc36253f864c16ea2f4beada9
      sudo yum install -y perl-IPC-Cmd curl zip unzip tar gcc-c++ make
      ./bootstrap-vcpkg.sh
      ./vcpkg install opentelemetry-cpp[otlp] --triplet=x64-linux-release
      rm -rf pkgme
      mkdir -p pkgme/lib pkgme/include
      cp installed/x64-linux-release/lib/libproto*.a pkgme/lib/
      cp installed/x64-linux-release/lib/libopentelemetry*.a pkgme/lib/
      cp installed/x64-linux-release/lib/libz.a pkgme/lib/
      # libcurl.a build on rocky 8.5 depends on fnctl64 which isn't available in our sysroot.
      # Until the sysroot is updated to match our new minspec, try using curl from the old
      # sysroot (see the build_curl_centos7 dependency).
      #cp installed/x64-linux-release/lib/libcurl.a pkgme/lib/
      cp curl-libs/libcurl.a pkgme/lib/
      cp installed/x64-linux-release/lib/libcrypto.a pkgme/lib/
      cp installed/x64-linux-release/lib/libssl.a pkgme/lib/
      cp -r installed/x64-linux-release/include/opentelemetry pkgme/include/
      cp -r installed/x64-linux-release/include/google pkgme/include/
      echo -e "# vcpkg's LICENSE.txt\n" > pkgme/LICENSE.md
      cat LICENSE.txt >> pkgme/LICENSE.md
      echo -e "\n# vcpkg's NOTICE.txt\n" >> pkgme/LICENSE.md
      cat NOTICE.txt >> pkgme/LICENSE.md
      echo -e "\n# curl\n" >> pkgme/LICENSE.md
      cat installed/x64-linux-release/share/curl/copyright >> pkgme/LICENSE.md
      echo -e "\n# openssl\n" >> pkgme/LICENSE.md
      cat installed/x64-linux-release/share/openssl/copyright >> pkgme/LICENSE.md
      echo -e "\n# opentelemetry-cpp\n" >> pkgme/LICENSE.md
      cat installed/x64-linux-release/share/opentelemetry-cpp/copyright >> pkgme/LICENSE.md
      echo -e "\n# protobuf\n" >> pkgme/LICENSE.md
      cat installed/x64-linux-release/share/protobuf/copyright >> pkgme/LICENSE.md
      echo -e "\n# zlib\n" >> pkgme/LICENSE.md
      cat installed/x64-linux-release/share/zlib/copyright >> pkgme/LICENSE.md
      cd pkgme
      chmod -R u+w .
      find . -exec touch -d 1970-01-01 '{}' ';'
      rm -f ../opentelemetry-cpp-lin-amd64.zip
      zip -r ../opentelemetry-cpp-lin-amd64.zip *
      cd ..
      rm -rf pkgme
  artifacts:
    opentelemetry-cpp-stevedore-pkg:
      paths:
        - opentelemetry-cpp-lin-amd64.zip
  dependencies:
    - .yamato/build.yml#build_curl_centos7

build_curl_centos7:
  name: build curl on centos7
  agent:
    image: slough-ops/centos-7-base:v0.3.2-1010409
    flavor: b1.large
    type: Unity::VM
  commands:
    - |
      set -euxo pipefail
      git checkout 16f2ec16633791bcc36253f864c16ea2f4beada9
      sudo yum install -y perl-IPC-Cmd curl zip unzip tar gcc-c++ make
      ./bootstrap-vcpkg.sh
      ./vcpkg install curl --triplet=x64-linux-release
      cp -ax installed/x64-linux-release/lib curl-libs
  artifacts:
    curl-libs:
      paths:
        - curl-libs/**

build_mac_amd64:
  name: build mac amd64
  agent:
    # This is the "minimal spec" image we test against.
    image: build-system/bee-macos-10.15-xcode:v0.1.2-1006613
    flavor: b1.large
    type: Unity::VM::osx
  commands:
    - |
      set -euxo pipefail
      git checkout 16f2ec16633791bcc36253f864c16ea2f4beada9
      brew install pkg-config
      ./bootstrap-vcpkg.sh
      cp -f triplets/x64-osx.cmake triplets/x64-osx-10.14.cmake
      echo "set(VCPKG_OSX_DEPLOYMENT_TARGET 10.14)" >> triplets/x64-osx-10.14.cmake
      echo "set(VCPKG_C_FLAGS -mmacosx-version-min=10.14)" >> triplets/x64-osx-10.14.cmake
      echo "set(VCPKG_CXX_FLAGS -mmacosx-version-min=10.14)" >> triplets/x64-osx-10.14.cmake
      ./vcpkg install opentelemetry-cpp[otlp] --triplet=x64-osx-10.14
      rm -rf pkgme
      mkdir -p pkgme/lib pkgme/include
      cp installed/x64-osx-10.14/lib/libproto*.a pkgme/lib/
      cp installed/x64-osx-10.14/lib/libopentelemetry*.a pkgme/lib/
      cp installed/x64-osx-10.14/lib/libz.a pkgme/lib/
      cp installed/x64-osx-10.14/lib/libcurl.a pkgme/lib/
      cp installed/x64-osx-10.14/lib/libcrypto.a pkgme/lib/
      cp installed/x64-osx-10.14/lib/libssl.a pkgme/lib/
      cp -r installed/x64-osx-10.14/include/opentelemetry pkgme/include/
      cp -r installed/x64-osx-10.14/include/google pkgme/include/
      echo -e "# vcpkg's LICENSE.txt\n" > pkgme/LICENSE.md
      cat LICENSE.txt >> pkgme/LICENSE.md
      echo -e "\n# vcpkg's NOTICE.txt\n" >> pkgme/LICENSE.md
      cat NOTICE.txt >> pkgme/LICENSE.md
      echo -e "\n# curl\n" >> pkgme/LICENSE.md
      cat installed/x64-osx-10.14/share/curl/copyright >> pkgme/LICENSE.md
      echo -e "\n# openssl\n" >> pkgme/LICENSE.md
      cat installed/x64-osx-10.14/share/openssl/copyright >> pkgme/LICENSE.md
      echo -e "\n# opentelemetry-cpp\n" >> pkgme/LICENSE.md
      cat installed/x64-osx-10.14/share/opentelemetry-cpp/copyright >> pkgme/LICENSE.md
      echo -e "\n# protobuf\n" >> pkgme/LICENSE.md
      cat installed/x64-osx-10.14/share/protobuf/copyright >> pkgme/LICENSE.md
      echo -e "\n# zlib\n" >> pkgme/LICENSE.md
      cat installed/x64-osx-10.14/share/zlib/copyright >> pkgme/LICENSE.md
      cd pkgme
      chmod -R u+w .
      rm -f ../opentelemetry-cpp-mac-amd64.zip
      zip -r ../opentelemetry-cpp-mac-amd64.zip *
      cd ..
      rm -rf pkgme
  artifacts:
    opentelemetry-cpp-stevedore-pkg:
      paths:
        - opentelemetry-cpp-mac-amd64.zip

build_mac_arm64:
  name: build mac arm64
  agent:
    image: build-system/unity-macos-10.15:v1.0.3-1026271
    flavor: b1.large
    type: Unity::VM::osx
  commands:
    - |
      set -euxo pipefail
      git checkout 16f2ec16633791bcc36253f864c16ea2f4beada9
      brew install pkg-config
      ./bootstrap-vcpkg.sh
      cp -f triplets/community/arm64-osx.cmake triplets/community/arm64-osx-10.14.cmake
      echo "set(VCPKG_OSX_DEPLOYMENT_TARGET 10.14)" >> triplets/community/arm64-osx-10.14.cmake
      echo "set(VCPKG_C_FLAGS -mmacosx-version-min=10.14)" >> triplets/community/arm64-osx-10.14.cmake
      echo "set(VCPKG_CXX_FLAGS -mmacosx-version-min=10.14)" >> triplets/community/arm64-osx-10.14.cmake
      ./vcpkg install opentelemetry-cpp[otlp] --triplet=arm64-osx-10.14
      rm -rf pkgme
      mkdir -p pkgme/lib pkgme/include
      cp installed/arm64-osx-10.14/lib/libproto*.a pkgme/lib/
      cp installed/arm64-osx-10.14/lib/libopentelemetry*.a pkgme/lib/
      cp installed/arm64-osx-10.14/lib/libz.a pkgme/lib/
      cp installed/arm64-osx-10.14/lib/libcurl.a pkgme/lib/
      cp installed/arm64-osx-10.14/lib/libcrypto.a pkgme/lib/
      cp installed/arm64-osx-10.14/lib/libssl.a pkgme/lib/
      cp -r installed/arm64-osx-10.14/include/opentelemetry pkgme/include/
      cp -r installed/arm64-osx-10.14/include/google pkgme/include/
      echo -e "# vcpkg's LICENSE.txt\n" > pkgme/LICENSE.md
      cat LICENSE.txt >> pkgme/LICENSE.md
      echo -e "\n# vcpkg's NOTICE.txt\n" >> pkgme/LICENSE.md
      cat NOTICE.txt >> pkgme/LICENSE.md
      echo -e "\n# curl\n" >> pkgme/LICENSE.md
      cat installed/arm64-osx-10.14/share/curl/copyright >> pkgme/LICENSE.md
      echo -e "\n# openssl\n" >> pkgme/LICENSE.md
      cat installed/arm64-osx-10.14/share/openssl/copyright >> pkgme/LICENSE.md
      echo -e "\n# opentelemetry-cpp\n" >> pkgme/LICENSE.md
      cat installed/arm64-osx-10.14/share/opentelemetry-cpp/copyright >> pkgme/LICENSE.md
      echo -e "\n# protobuf\n" >> pkgme/LICENSE.md
      cat installed/arm64-osx-10.14/share/protobuf/copyright >> pkgme/LICENSE.md
      echo -e "\n# zlib\n" >> pkgme/LICENSE.md
      cat installed/arm64-osx-10.14/share/zlib/copyright >> pkgme/LICENSE.md
      cd pkgme
      chmod -R u+w .
      rm -f ../opentelemetry-cpp-mac-arm64.zip
      zip -r ../opentelemetry-cpp-mac-arm64.zip *
      cd ..
      rm -rf pkgme
  artifacts:
    opentelemetry-cpp-stevedore-pkg:
      paths:
        - opentelemetry-cpp-mac-arm64.zip

build_windows:
  name: build windows
  agent:
    image: cds-ops/win10-vs2017:v0.0.7-942646
    flavor: b1.xlarge
    type: Unity::VM
  interpreter: powershell
  commands:
    - git checkout 16f2ec16633791bcc36253f864c16ea2f4beada9

    - |
      $ErrorActionPreference = "Stop"
      trap { $host.SetShouldExit(1) }
      .\bootstrap-vcpkg.bat
      .\vcpkg install opentelemetry-cpp[otlp]:x64-windows-static
      mkdir pkgme
      mkdir pkgme\include
      mkdir pkgme\lib
      Copy-Item -Force -Path installed\x64-windows-static\lib\libproto*.lib -Destination pkgme\lib\
      Copy-Item -Force -Path installed\x64-windows-static\lib\libcrypto.lib -Destination pkgme\lib\
      Copy-Item -Force -Path installed\x64-windows-static\lib\libssl.lib -Destination pkgme\lib\
      Copy-Item -Force -Path installed\x64-windows-static\lib\opentelemetry*.lib -Destination pkgme\lib\
      Copy-Item -Force -Path installed\x64-windows-static\lib\libcurl.lib -Destination pkgme\lib\
      Copy-Item -Force -Path installed\x64-windows-static\lib\zlib.lib -Destination pkgme\lib\
      Copy-Item -Force -Recurse -Path installed\x64-windows-static\include\opentelemetry -Destination pkgme\include\opentelemetry
      Copy-Item -Force -Recurse -Path installed\x64-windows-static\include\google -Destination pkgme\include\google
      echo "# vcpkg's LICENSE.txt" > pkgme\LICENSE.md.utf16
      echo "" >> pkgme\LICENSE.md.utf16
      cat LICENSE.txt >> pkgme\LICENSE.md.utf16
      echo "" >> pkgme\LICENSE.md.utf16
      echo "# vcpkg's NOTICE.txt" >> pkgme\LICENSE.md.utf16
      echo "" >> pkgme\LICENSE.md.utf16
      cat NOTICE.txt >> pkgme\LICENSE.md.utf16
      echo "" >> pkgme\LICENSE.md.utf16
      echo "# curl" >> pkgme\LICENSE.md.utf16
      echo "" >> pkgme\LICENSE.md.utf16
      cat installed\x64-windows-static\share\curl\copyright >> pkgme\LICENSE.md.utf16
      echo "" >> pkgme\LICENSE.md.utf16
      echo "# openssl" >> pkgme\LICENSE.md.utf16
      echo "" >> pkgme\LICENSE.md.utf16
      cat installed\x64-windows-static\share\openssl\copyright >> pkgme\LICENSE.md.utf16
      echo "" >> pkgme\LICENSE.md.utf16
      echo "# opentelemetry-cpp" >> pkgme\LICENSE.md.utf16
      echo "" >> pkgme\LICENSE.md.utf16
      cat installed\x64-windows-static\share\opentelemetry-cpp\copyright >> pkgme\LICENSE.md.utf16
      echo "" >> pkgme\LICENSE.md.utf16
      echo "# protobuf" >> pkgme\LICENSE.md.utf16
      echo "" >> pkgme\LICENSE.md.utf16
      cat installed\x64-windows-static\share\protobuf\copyright >> pkgme\LICENSE.md.utf16
      echo "" >> pkgme\LICENSE.md.utf16
      echo "# zlib" >> pkgme\LICENSE.md.utf16
      echo "" >> pkgme\LICENSE.md.utf16
      cat installed\x64-windows-static\share\zlib\copyright >> pkgme\LICENSE.md.utf16
      Get-Content pkgme\LICENSE.md.utf16 | Set-Content -Encoding utf8 pkgme\LICENSE.md
      rm pkgme\LICENSE.md.utf16
      cd pkgme
      7z.exe a -tzip ..\opentelemetry-cpp-win-amd64.zip *
      cd ..
      rm -r pkgme
  artifacts:
    opentelemetry-cpp-stevedore-pkg:
      paths:
        - opentelemetry-cpp-win-amd64.zip
